apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  name: crossplane-gcp-vm
spec:
  forProvider:
    zone: us-central1-a
    machineType: e2-micro
    bootDisk:
      - initializeParams:
          - imageId: projects/debian-cloud/global/images/family/debian-10
            size: 20
    networkInterface:
      - network: default
        accessConfig:
          - natIp: ""
    tags:
      - crossplane
      - dev
    metadata:
      startup-script: |
        #!/bin/bash
        apt-get update
        apt-get install -y nginx
        systemctl start nginx
  providerConfigRef:
    name: gcp-config