apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/k8s-local-clouds.git # Replace with your actual repo
    targetRevision: HEAD
    path: deployment/simple-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: local-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true