apiVersion: database.azure.upbound.io/v1beta1
kind: PostgreSQLServer
metadata:
  name: crossplane-azure-postgres
spec:
  forProvider:
    location: westeurope
    resourceGroupName: crossplane-resources
    sku:
      - name: B_Gen5_1
        tier: Basic
        family: Gen5
        capacity: 1
    storageProfile:
      - storageMb: 5120
        backupRetentionDays: 7
        geoRedundantBackup: Disabled
    version: "11"
    administratorLogin: postgresadmin
    administratorLoginPassword: 
      name: azure-db-password
      key: password
      namespace: crossplane-system
    sslEnforcement: Enabled
    tags:
      Environment: dev
      ManagedBy: crossplane
  providerConfigRef:
    name: azure-config
  writeConnectionSecretToRef:
    namespace: default
    name: azure-postgres-connection
---
apiVersion: database.azure.upbound.io/v1beta1
kind: PostgreSQLDatabase
metadata:
  name: crossplane-azure-db
spec:
  forProvider:
    resourceGroupName: crossplane-resources
    serverName: crossplane-azure-postgres
    charset: UTF8
    collation: English_United States.1252
  providerConfigRef:
    name: azure-config
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-db-password
  namespace: crossplane-system
type: Opaque
data:
  # In production, use a secure password management solution
  # For demo purposes, this is a base64-encoded string: stR0ngPa$$w0rd!
  password: c3RSMG5nUGEkJHcwcmQh